app:
  env: ${APP_ENV}
  name: todo-list
  version: 0.0.1

server:
  http:
    addr: ${HTTP_ADDR}
    tls:
      enable: false 
      server-cert-path: ./certs/server.crt
      server-key-path: ./certs/server.key
  read-timeout: 2s
  write-timeout: 2s
  idle-timeout: 30s

postgres:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  sslmode: disable
  auth:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    dbname: ${POSTGRES_DBNAME}
  conn:
    max-idles: 15
    max-opens: 5
    max-idle-time: 30m
    max-lifetime: 15m

redis:
  addr: ${REDIS_ADDR}
  auth:
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
    db: ${REDIS_DB}
  user-ttl: 5m
  group-ttl: 5m

session:
  token-ttl: 168h
  secret-key: ${SECRET_KEY}